---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openclaw-secrets
    template:
      engineVersion: v2
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
  dataFrom:
    - extract:
        key: openclaw-secrets
