githubConfigUrl: https://github.com/smauermann/homelab
githubConfigSecret: github-app-credentials
minRunners: 1
maxRunners: 4
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-single-replica
    resources:
      requests:
        storage: 10Gi
controllerServiceAccount:
  name: actions-runner-controller-gha-rs-controller
  namespace: arc-system
template:
  spec:
    serviceAccountName: homelab-runner
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        # renovate: datasource=docker depName=ghcr.io/smauermann/actions-runner
        image: ghcr.io/smauermann/actions-runner:2.336.0@sha256:40c5df7551ee7f267992ac6c196c979d4837992ab962e0d5a61c42b29e2f60c2
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
