githubConfigUrl: https://github.com/smauermann/homelab
githubConfigSecret: github-app-credentials
minRunners: 1
maxRunners: 4
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-single-replica
    resources:
      requests:
        storage: 10Gi
controllerServiceAccount:
  name: actions-runner-controller-gha-rs-controller
  namespace: arc-system
template:
  spec:
    serviceAccountName: homelab-runner
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        # renovate: datasource=docker depName=ghcr.io/smauermann/actions-runner
        image: ghcr.io/smauermann/actions-runner:2.334.0@sha256:1f19282a7ebd1b20bb08711fb7c224a61b8c7e062fd5ebfcc0f79a1f1e99e28f
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
