githubConfigUrl: https://github.com/smauermann/homelab
githubConfigSecret: github-app-credentials
minRunners: 1
maxRunners: 4
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-single-replica
    resources:
      requests:
        storage: 10Gi
controllerServiceAccount:
  name: actions-runner-controller-gha-rs-controller
  namespace: arc-system
template:
  spec:
    serviceAccountName: homelab-runner
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        # renovate: datasource=docker depName=ghcr.io/smauermann/actions-runner
        image: ghcr.io/smauermann/actions-runner:2.335.1@sha256:4c17f4045d11af9e88750ddcca6dff43924da1413c05e79cef7f39584b78432e
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
