apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    template:
      data:
        admin_password: "{{ .admin_password }}"
        admin_username: "{{ .admin_username }}"
        secret_key: "{{ .secret_key }}"
        provider-config: |
          {"openid_connect":{"SCOPE":["openid","profile","email","groups"],"APPS":[{"provider_id":"pocket-id","name":"Pocket ID","client_id":"{{ index . "oidc-client-id" }}","secret":"{{ index . "oidc-client-secret" }}","settings":{"server_url":"https://pid.costanza.cloud/.well-known/openid-configuration"}}]}}
  dataFrom:
    - extract:
        key: paperless
