# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.3/charts/library/common/values.schema.json
---
controllers:
  paperless:
    replicas: 1
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    containers:
      app:
        image:
          repository: ghcr.io/paperless-ngx/paperless-ngx
          tag: 2.20.10@sha256:07a0b4ba01ce377c82a0636e16c0c3d931fde5b7e9304de6601986cc42d9b6e6
        env:
          PAPERLESS_SECRET_KEY:
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: secret_key
          PAPERLESS_URL: https://paperless.costanza.cloud
          PAPERLESS_PORT: "8000"
          PAPERLESS_TIME_ZONE: "Europe/Berlin"
          PAPERLESS_WEBSERVER_WORKERS: "2"
          PAPERLESS_TASK_WORKERS: "2"
          # Configure folders
          PAPERLESS_DATA_DIR: /data/local/data
          PAPERLESS_EXPORT_DIR: /data/nfs/export
          PAPERLESS_MEDIA_ROOT: /data/nfs/media
          # Disable folder consumer (upload via app/web only)
          PAPERLESS_CONSUMER_DISABLE: "true"
          # Configure OCR
          PAPERLESS_OCR_LANGUAGE: deu+eng
          PAPERLESS_OCR_SKIP_ARCHIVE_FILE: with_text
          PAPERLESS_OCR_PAGES: "5"
          # Configure redis integration
          PAPERLESS_REDIS: redis://paperless-dragonfly.paperless.svc.cluster.local:6379
          # Configure user permissions
          USERMAP_UID: "1000"
          USERMAP_GID: "1000"
          # Configure admin user
          PAPERLESS_ADMIN_USER:
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: admin_username
          PAPERLESS_ADMIN_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: admin_password
          # Configure SSO
          PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
          PAPERLESS_SOCIALACCOUNT_PROVIDERS:
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: provider-config
          PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
          PAPERLESS_SOCIALACCOUNT_EMAIL_AUTHENTICATION: "true"
          PAPERLESS_SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT: "true"
          PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 25m
            memory: 2Gi
          limits:
            memory: 6Gi

service:
  app:
    controller: paperless
    ports:
      http:
        port: 8000

route:
  app:
    kind: HTTPRoute
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Paperless
      gethomepage.dev/description: Documents
      gethomepage.dev/group: Applications
      gethomepage.dev/icon: paperless.png
      gethomepage.dev/pod-selector: >-
        app in (
          paperless
        )
    parentRefs:
      - name: private
        kind: Gateway
        namespace: envoy-gateway-system
    hostnames:
      - paperless.costanza.cloud

persistence:
  data:
    existingClaim: paperless-data
    advancedMounts:
      paperless:
        app:
          - path: /data/local
  nfs:
    type: nfs
    server: nas.internal
    path: /volume1/homelab/documents
    globalMounts:
      - path: /data/nfs
