controllers:
  iperf3:
    containers:
      app:
        env:
          TZ: "Europe/Berlin"
        image:
          repository: networkstatic/iperf3
          tag: latest@sha256:c1e4a239a83d1d60975bce1c9b7661af5517e362bf335f66a2c5b6adaeb4f19f
        args:
          - -s
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

service:
  app:
    type: LoadBalancer
    controller: iperf3
    annotations:
      io.cilium/lb-ipam-ips: 192.168.30.31
    ports:
      iperf:
        port: 5201
