controllers:
  iperf3:
    containers:
      app:
        env:
          TZ: "Europe/Berlin"
        image:
          repository: networkstatic/iperf3
          tag: latest@sha256:aaa9e59dcd624990c2493449c65da4aae0d9c7fed6f205c4d2152283abc5410e
        args:
          - -s
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

service:
  app:
    type: LoadBalancer
    controller: iperf3
    annotations:
      io.cilium/lb-ipam-ips: 192.168.30.31
    ports:
      iperf:
        port: 5201
